version: '3.5'

services:
  chaingraph-postgres:
    container_name: chaingraph-postgres
    image: postgres:latest
    volumes: 
      - chaingraph-pgdata:/var/lib/postgresql/data_chaingraph
    ports:
      - '5432:5432'
    environment:
      PGPORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: chaingraph
      DB_NAME: chaingraph
      DB_USER: user
      DB_PASSWORD: pass

  chaingraph-hasura:
    container_name: chaingraph-hasura
    build: ./
    image: chaingraph-hasura:local
    ports:
      - "3333:3333"
    restart: always
    environment:
      # https://hasura.io/docs/1.0/graphql/core/deployment/graphql-engine-flags/reference.html
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:pass@postgres:5432/chaingraph?sslmode=disable
      HASURA_GRAPHQL_ADMIN_SECRET: super-secret
      HASURA_GRAPHQL_SERVER_PORT: 3333
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_ENABLED_APIS: graphql,metadata
      # HASURA_GRAPHQL_AUTH_HOOK: https://auth-server.app/auth
      HASURA_GRAPHQL_AUTH_HOOK_MODE: POST
    command:
      - graphql-engine
      - serve
    depends_on:
      - chaingraph-postgres

volumes:
  chaingraph-pgdata:

networks:
  default:
    name: chaingraph
    # driver: bridge

    